apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nginx
spec:
  selector:
    matchLabels:
      app: argocd-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: argocd-nginx
    spec:
      containers:
      - name: argocd-nginx
        image: nginx:latest
        ports:
        - containerPort: 80